### PR TITLE
Use correct exception type

### LINKED ISSUE #29: Version 2.0.0: KeyError: 'olarm_arm_code'
Just updated to 2.0.0 and it fails to start up.

```
Logger: homeassistant.config_entries
Source: custom_components/olarm_sensors/__init__.py:43
Integration: Olarm Sensors ([documentation](https://github.com/rainepretorius/olarm-ha-integration/blob/main/README.md), [issues](https://github.com/rainepretorius/olarm-ha-integration/issues))
First occurred: 09:10:23 (1 occurrences)
Last logged: 09:10:23

Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/olarm_sensors/__init__.py", line 43, in async_setup_entry
    not config_entry.options[CONF_ALARM_CODE]
KeyError: 'olarm_arm_code'
```

### PR DESCRIPTION
**Pull request by drzoidberg33**
Fixes #29 

I spotted the error and it is an easy fix.

### CODE REVIEW

**Review by rainepretorius — CHANGES_REQUESTED** [review]
The class must inherit from BaseException, else it throws an error and does not work.

**Comment by drzoidberg33** [comment]
Thanks, I should just get this project set up in a dev environment so I can help out. I just tested this directly on my HA instance where it appeared to work 😅

**Comment by drzoidberg33** [comment]
> The class must inherit from BaseException, else it throws an error and does not work.

I'm confused as to what exceptions.py is supposed to be doing here, the comment at the top states it is storing them in the home assistant format - could you point me to the documentation for this?

I'm still unsure how a `KeyError` exception will get caught here when we have no condition for it.

**Comment by jonathankretzmer** [comment]
I had the exact same issue, applied the proposed fix from @drzoidberg33, and it's working fine now.

**Comment by drzoidberg33** [comment]
This was resolved in https://github.com/rainepretorius/olarm-ha-integration/commit/3577751081fbef44420a3254fb222e1b768ed13a

Thanks @rainepretorius!

**Pull request closed without merging**
