### PR TITLE
Fix for missing PGMs and Ukeys

### PR DESCRIPTION
**Pull request by Cha0s2nd**

### CODE REVIEW

**Comment by Cha0s2nd** [comment]
#90

**Review by rainepretorius — COMMENTED** [review]
Looks all good. Does this code work? I am unable to test it as my Olarm stopped functioning and thus I am unable to perform my usual tests.

**Comment by Cha0s2nd** [comment]
> Looks all good. Does this code work? I am unable to test it as my Olarm stopped functioning and thus I am unable to perform my usual tests.

I had to make a few tweaks but works for me and him.

**Comment by rainepretorius** [comment]
> > Looks all good. Does this code work? I am unable to test it as my Olarm stopped functioning and thus I am unable to perform my usual tests.
> 
> I had to make a few tweaks but works for me and him. 

👍

**Pull request merged**
